# -*- coding: utf-8 -*-
"""
/***************************************************************************
 index_extractor
                                 A QGIS plugin
 This plug-in extract several Vegetal Index from Sentinel-2 data
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2018-03-08
        copyright            : (C) 2018 by Javier Balanzategui Sánchez
        email                : javier.balanzategui.sanchez@alumnos.upm.es
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load index_extractor class from file index_extractor.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .main_index_extractor import index_extractor
    return index_extractor(iface)
